spring.application.name=backend
server.port=80
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.url=jdbc:sqlite:assets/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

storage.pdfpath=assets/pdf
storage.thumbnailpath=assets/thumbnail

jwt.secret=${JWT_SECRET}
jwt.expiration-time=${JWT_EXPIRATION_TIME}

admin.username=${ADMIN_USERNAME}
admin.password=${ADMIN_PASSWORD}