spring.application.name=backend
server.port=80
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.datasource.url=jdbc:sqlite:assets/app.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

storage.pdfpath=assets/pdf
storage.htmlpath=assets/html
jwt.secret=${JWT_SECRET}
jwt.expiration-time=${JWT_EXPIRATION_TIME}
external.pdf2html-server.url=${PDF2HTML_SERVER_URL}